// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha2

import xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"

// GetCondition of this AsyncDisposableRequest.
func (mg *AsyncDisposableRequest) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this AsyncDisposableRequest.
func (mg *AsyncDisposableRequest) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this AsyncDisposableRequest.
func (mg *AsyncDisposableRequest) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this AsyncDisposableRequest.
func (mg *AsyncDisposableRequest) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this AsyncDisposableRequest.
func (mg *AsyncDisposableRequest) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this AsyncDisposableRequest.
func (mg *AsyncDisposableRequest) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this AsyncDisposableRequest.
func (mg *AsyncDisposableRequest) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this AsyncDisposableRequest.
func (mg *AsyncDisposableRequest) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this AsyncDisposableRequest.
func (mg *AsyncDisposableRequest) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this AsyncDisposableRequest.
func (mg *AsyncDisposableRequest) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}
