apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-http-async
  annotations:
    meta.crossplane.io/maintainer: Taras Zubrei
    meta.crossplane.io/source: github.com/Antrakos/provider-http-async
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      A Crossplane provider for asynchronous HTTP requests.
spec:
  capabilities:
    - safe-start
