name: CI

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - 'v*'
  pull_request: {}
  workflow_dispatch: {}

env:
  GO_VERSION: '1.25.11'
  DOCKER_BUILDX_VERSION: 'v0.23.0'
  CROSSPLANE_CLI_VERSION: 'v2.3.1'

  # The package to push, without a version tag. Published to GHCR.
  XPKG: ghcr.io/${{ github.repository }}

jobs:
  detect-noop:
    runs-on: ubuntu-22.04
    outputs:
      noop: ${{ steps.noop.outputs.should_skip }}
    steps:
      - name: Detect No-op Changes
        id: noop
        uses: fkirc/skip-duplicate-actions@v5.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths_ignore: '["**.md", "**.png", "**.jpg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'

  lint:
    runs-on: ubuntu-22.04
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check go mod tidy
        run: go mod tidy && git diff --exit-code go.mod go.sum

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.12.2

  check-diff:
    runs-on: ubuntu-22.04
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check generated code is up to date
        id: check-diff
        run: go generate ./... && git diff --exit-code

      - name: Show diff
        if: failure() && steps.check-diff.outcome == 'failure'
        run: git diff

  unit-tests:
    runs-on: ubuntu-22.04
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Unit Tests
        run: go test -v -cover ./...

      - name: Publish Unit Test Coverage
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          file: _output/tests/linux_amd64/coverage.txt

  # Build single-platform packages in parallel, then merge into a multi-platform push.
  build:
    runs-on: ubuntu-22.04
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'
    strategy:
      fail-fast: true
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
        with:
          version: ${{ env.DOCKER_BUILDX_VERSION }}

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Build Runtime
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          platforms: linux/${{ matrix.arch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: image
          build-args: |
            GO_VERSION=${{ env.GO_VERSION }}
          outputs: type=docker,dest=runtime-${{ matrix.arch }}.tar

      - name: Setup the Crossplane CLI
        run: 'curl -sfL https://cli.crossplane.io/install.sh | XP_VERSION=${{ env.CROSSPLANE_CLI_VERSION }} sh'

      - name: Build Package
        run: ./crossplane xpkg build --package-file=${{ matrix.arch }}.xpkg --package-root=package/ --embed-runtime-image-tarball=runtime-${{ matrix.arch }}.tar

      - name: Upload Single-Platform Package
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: package-${{ matrix.arch }}
          path: "*.xpkg"
          if-no-files-found: error
          retention-days: 1

  # Download single-platform packages and push as a multi-platform package.
  push:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Download Single-Platform Packages
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: "!*.dockerbuild"
          path: .
          merge-multiple: true

      - name: Setup the Crossplane CLI
        run: 'curl -sfL https://cli.crossplane.io/install.sh | XP_VERSION=${{ env.CROSSPLANE_CLI_VERSION }} sh'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Multi-Platform Package Version
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            echo "XPKG_VERSION=${{ github.ref_name }}" >> "$GITHUB_ENV"
          else
            echo "XPKG_VERSION=v0.0.0-$(date -d@$(git show -s --format=%ct) +%Y%m%d%H%M%S)-$(git rev-parse --short=12 HEAD)" >> "$GITHUB_ENV"
          fi

      - name: Push Multi-Platform Package to GitHub Container Registry
        run: "./crossplane --verbose xpkg push --package-files $(echo *.xpkg|tr ' ' ,) ${XPKG@L}:${{ env.XPKG_VERSION }}"

  # Create a GitHub Release on v* tag pushes.
  release:
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    needs:
      - push
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Generate Release Notes
        id: notes
        uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5 # v4.8.0
        with:
          config: cliff.toml
          args: --latest --strip header

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          {
            cat "${{ steps.notes.outputs.changelog }}"
            echo
            echo "**Package:** \`${XPKG@L}:${{ github.ref_name }}\`"
            echo "**Full Changelog:** ${{ github.server_url }}/${{ github.repository }}/commits/${{ github.ref_name }}"
          } > release-notes.md
          gh release create "${{ github.ref_name }}" \
            --title "${{ github.ref_name }}" \
            --verify-tag \
            --notes-file release-notes.md
